-- POPULATE CUSTOMERS TABLE --

INSERT ALL
	INTO CUSTOMERS
	(C_ID,FIRST_NAME,LAST_NAME,PASSWORD,LAST_LOGIN,EMAIL,HOME_NUMBER,MOBILE_NUMBER)
	VALUES
	(1, 'David', 'Portillo', 'password1', '21/JAN/2017 04:00:00', 'david@gmail.com', 230300020, 453043204)
	INTO CUSTOMERS
	(C_ID,FIRST_NAME,LAST_NAME,PASSWORD,LAST_LOGIN,EMAIL,HOME_NUMBER,MOBILE_NUMBER)
	VALUES
	(2, 'Lawrence', 'Broomfield', 'password1', '21/JAN/2017 04:00:00', 'lawrence@gmail.com', 345246642, 964739432)
	INTO CUSTOMERS
	(C_ID,FIRST_NAME,LAST_NAME,PASSWORD,LAST_LOGIN,EMAIL,HOME_NUMBER,MOBILE_NUMBER)
	VALUES
	(3, 'Franklin', 'Berry', 'password1', '21/JAN/2017 04:00:00', 'Franklin@gmail.com', 947582443, 534254321)
SELECT 1 FROM DUAL;

-- POPULATE LOCATIONS_TYPES

INSERT ALL
	INTO LOCATIONS_TYPES(LT_ID,LOCATION_NAME) VALUES(1, 'Billing')
	INTO LOCATIONS_TYPES(LT_ID,LOCATION_NAME) VALUES(2, 'Other')
SELECT 1 FROM DUAL;

-- POPULATE CUSTOMERS_LOCATIONS 

INSERT ALL
	INTO CUSTOMERS_LOCATIONS
	(CL_ID,LT_ID,STREET_ADDRESS,CITY,STATE,ZIP_CODE,C_ID) 
	VALUES
	(1, 1, 'Fake Address','Arlington', 'VA', '22207', 1)
	INTO CUSTOMERS_LOCATIONS
	(CL_ID,LT_ID,STREET_ADDRESS,CITY,STATE,ZIP_CODE,C_ID) 
	VALUES
	(2, 2, 'Fake Address','Phoenix', 'AZ', '878878', 1)
	INTO CUSTOMERS_LOCATIONS
	(CL_ID,LT_ID,STREET_ADDRESS,CITY,STATE,ZIP_CODE,C_ID) 
	VALUES
	(2, 2, 'Fake Address','MyCity', 'MyState', '23424', 2)
	INTO CUSTOMERS_LOCATIONS
	(CL_ID,LT_ID,STREET_ADDRESS,CITY,STATE,ZIP_CODE,C_ID) 
	VALUES
	(3, 1, 'Fake Address','Kentucky City', 'Kentucky', '23424', 3)
SELECT 1 FROM DUAL;

-- POPULATE MEAL_TYPES

INSERT ALL
	INTO MEAL_TYPES
	(MT_ID,NAME)
	VALUES
	(1,'Vegan')
	INTO MEAL_TYPES
	(MT_ID,NAME)
	VALUES
	(2,'Non-Vegan')
SELECT 1 FROM DUAL;

-- POPULATE MEALS

INSERT ALL
	INTO MEALS
	(M_ID,NAME,DESCRIPTION,PRICE,IMAGE_PATH,MEAL_OF_DAY,MT_ID)
	VALUES
	()
SELECT 1 FROM DUAL;
