
---------------ORIGINAL SCRIPT---------------
--Didn't work for some reason
--DROP TABLE CUSTOMERS;
--DROP TABLE LOCATIONS_TYPES;
--DROP TABLE CUSTOMERS_LOCATIONS;
--DROP TABLE MEAL_TYPES;
--DROP TABLE MEALS;
--DROP TABLE ORDER_STATUS;
--DROP TABLE ORDERS;
--DROP TABLE ORDER_MEALS;
--DROP TABLE PAYMENT_TYPES;
--DROP TABLE PAYMENTS;
--DROP TABLE CARD_TYPES;
--DROP TABLE CREDIT_CARDS;
--DROP TABLE CUSTOMERS_CREDIT_CARDS;
--DROP TABLE CREDIT_CARD_DETAILS;
--DROP TABLE DELIVERING_POINTS;
--DROP TABLE CUSTOMER_PROFILES;
--DROP TABLE ADMINS;

--------------CHANDLERS VERSION-------------

DROP TABLE ADMINS;
DROP TABLE CUSTOMER_PROFILES;
DROP TABLE DELIVERING_POINTS;
DROP TABLE CREDIT_CARD_DETAILS;
DROP TABLE CUSTOMERS_CREDIT_CARDS;
DROP TABLE CREDIT_CARDS;
DROP TABLE CARD_TYPES;
DROP TABLE PAYMENTS;
DROP TABLE PAYMENT_TYPES;
DROP TABLE ORDER_MEALS;
DROP TABLE ORDERS;
DROP TABLE ORDER_STATUS;
DROP TABLE MEALS;
DROP TABLE MEAL_TYPES;
DROP TABLE CUSTOMERS_LOCATIONS;
DROP TABLE LOCATIONS_TYPES;
DROP TABLE CUSTOMERS;

