-- ******* CUSTOMERS ******

CREATE TABLE CUSTOMERS (
	C_ID INT NOT NULL,
	FIRST_NAME VARCHAR2(15) NOT NULL,
	LAST_NAME  VARCHAR2(20) NOT NULL,
	PASSWORD   VARCHAR2(9),
	LAST_LOGIN DATE,
	EMAIL	   VARCHAR2(320),
	HOME_NUMBER    NUMBER(9) NOT NULL,
	MOBILE_NUMBER  NUMBER(9) NOT NULL,
	PRIMARY KEY (C_ID)
);

-- ******* CUSTOMERS_LOCATIONS ******

CREATE TABLE CUSTOMERS_LOCATIONS (
         CL_ID		INT PRIMARY KEY,
         LT_ID    	INT NOT NULL,
	 STREET_ADDRESS VARCHAR2(20) NOT NULL,
         CITY   	VARCHAR2(20) NOT NULL,
	 STATE		VARCHAR2(15) NOT NULL,
	 ZIP_CODE	VARCHAR2(5) NOT NULL, 
	 C_ID		INT NOT NULL,           
	 CONSTRAINT C_ID_FK FOREIGN KEY (C_ID) REFERENCES CUSTOMERS(C_ID)
	 ON DELETE CASCADE,
	 CONSTRAINT LT_ID_FK FOREIGN KEY (C_ID) REFERENCES CUSTOMERS(C_ID)
	 ON DELETE CASCADE
);

-- ******* LOCATIONS_TYPES ******

CREATE TABLE LOCATIONS_TYPES (
         LT_ID		INT NOT NULL,
         LOCATION_NAME	VARCHAR2(5) NOT NULL
);

-- ******* MEAL_TYPES ******

CREATE TABLE MEAL_TYPES (
         MT_ID		INT,
         NAME		VARCHAR(25),
	PRIMARY KEY(MT_ID)
);

-- ******* MEALS ******

CREATE TABLE MEALS (
    M_ID INT PRIMARY KEY,
    DESCRIPTION	VARCHAR(120) NOT NULL,
	NAME VARCHAR2(20) NOT NULL,
    PRICE DECIMAL(5,2) NOT NULL,
    IMAGE_PATH VARCHAR2(255) NOT NULL,
	MEAL_OF_DAY	DATE,
	MT_ID VARCHAR2(5) NOT NULL
);

-- ******* ORDER_STATUS ******

CREATE TABLE ORDER_STATUS (
         OS_ID		INT,
         NAME		VARCHAR(25),
	PRIMARY KEY(OS_ID)
);

-- ******* ORDERS ******

CREATE TABLE ORDERS(
		O_ID	INT NOT NULL PRIMARY KEY,
		ORDER_DATE	DATE,
		DELIVERY_DATE	DATE,
		ORDER_ON_HOLD	CHAR(1 BYTE),
		TIMES_CHANGED	INT
);

-- ******* ORDER_MEALS ******

CREATE TABLE ORDER_MEALS (
         OM_ID	   INT NOT NULL PRIMARY KEY
);


-- ******* PAYMENT_TYPES ******

CREATE TABLE PAYMENT_TYPES (
    PT_ID		INT PRIMARY KEY,
    PAYMENT_NAME	VARCHAR2(30)
);

-- ******* PAYMENTS ******

CREATE TABLE PAYMENTS (
    P_ID INT NOT NULL,
    PT_ID INT NOT NULL,
	O_ID INT NOT NULL,
	PRIMARY KEY(P_ID,O_ID),
	CONSTRAINT PT_ID_FK FOREIGN KEY(PT_ID) REFERENCES PAYMENT_TYPES(PT_ID)
	ON DELETE CASCADE,
	CONSTRAINT O_ID_FK FOREIGN KEY(O_ID) REFERENCES ORDERS(O_ID)
	ON DELETE CASCADE
);

-- ******* CARD_TYPES ******

CREATE TABLE CARD_TYPES(
	CT_ID	INT NOT NULL PRIMARY KEY,
	NAME	VARCHAR2(40)
);

-- ******* CREDIT_CARDS ******

CREATE TABLE CREDIT_CARDS(
	CC_ID INT NOT NULL PRIMARY KEY,
	NAME_ON_CARD	VARCHAR2(100),
	CARD_NUMBER	VARCHAR2(16),
	CT_ID		INT NOT NULL,
	CONSTRAINT CT_ID_FK FOREIGN KEY(CT_ID) REFERENCES CARD_TYPES(CT_ID)
	ON DELETE CASCADE
);

-- ******* CUSTOMERS_CREDIT_CARDS ******

CREATE TABLE CUSTOMERS_CREDIT_CARDS(
	CC_ID	INT NOT NULL,
	C_ID	INT NOT NULL,
	CONSTRAINT CC_ID_FK FOREIGN KEY(CC_ID) REFERENCES CREDIT_CARDS(CC_ID)
	ON DELETE CASCADE,
	CONSTRAINT C_ID2_FK FOREIGN KEY(C_ID) REFERENCES CUSTOMERS(C_ID)
	ON DELETE CASCADE,
	PRIMARY KEY(CC_ID,C_ID)
);

-- ******* CREDIT_CARD_DETAILS ******

CREATE TABLE CREDIT_CARD_DETAILS(
	P_ID	INT NOT NULL,
	CC_ID	INT NOT NULL,
	O_ID    INT NOT NULL,
	CONSTRAINT CC_ID2_FK FOREIGN KEY(CC_ID) REFERENCES CREDIT_CARDS(CC_ID)
	ON DELETE CASCADE,
	CONSTRAINT P_ID_FK FOREIGN KEY(P_ID,O_ID) REFERENCES PAYMENTS(P_ID, O_ID)
	ON DELETE CASCADE,
	PRIMARY KEY(P_ID)
);

-- ******* DELIVERING_POINTS ******

CREATE TABLE DELIVERING_POINTS (
         DP_ID		INT NOT NULL,
         STREET_ADDRESS VARCHAR2(20) NOT NULL,
	 CITY      	VARCHAR2(20) NOT NULL,
         STATE      	VARCHAR2(15) NOT NULL,
         ZIP_CODE  	CHAR(5),
         HOME_NUMBER    NUMBER(9) NOT NULL,
	PRIMARY KEY (DP_ID)
);

-- ******* DELIVERING_POINTS ******

CREATE TABLE CUSTOMER_PROFILES (
         CP_ID	   INT NOT NULL,
	 PRIMARY KEY (CP_ID)
);







