-- ******* DATABASE CONFIGURATION *******

CONNECT SA AS SYSDBA;

CREATE TABLESPACE new_tablespace20
DATAFILE 'C:\TEST\DATABASE20_FILE.dbf'
SIZE 20M AUTOEXTEND ON;

CREATE USER db_u20
IDENTIFIED BY pass
DEFAULT TABLESPACE new_tablespace20
/

GRANT DBA TO db_u20
/

CONNECT db_u20/pass

-- *********** CREATE TABLES ************


-- ******* CUSTOMERS ******

CREATE TABLE CUSTOMERS (
	C_ID INT NOT NULL,
	FIRST_NAME VARCHAR2(15) NOT NULL,
	LAST_NAME  VARCHAR2(20) NOT NULL,
	PASSWORD   VARCHAR2(9) NOT NULL ,
	LAST_LOGIN TIMESTAMP NOT NULL,
	EMAIL	   VARCHAR2(320),
	HOME_NUMBER    NUMBER(9) NOT NULL,
	MOBILE_NUMBER  NUMBER(9) NOT NULL,
	PRIMARY KEY (C_ID),
	CONSTRAINT UNIQUE_CUS_EMAIL UNIQUE(EMAIL)
);

CREATE SEQUENCE SEQ_CUSTOMERS MINVALUE 1 START WITH 1 INCREMENT BY 1;

-- ******* LOCATIONS_TYPES ******

CREATE TABLE LOCATIONS_TYPES (
    LT_ID INT NOT NULL PRIMARY KEY,
    LOCATION_NAME VARCHAR2(30) NOT NULL,
	CONSTRAINT UNIQUE_LN UNIQUE(LOCATION_NAME)
);

CREATE SEQUENCE SEQ_LOC_TYPES MINVALUE 1 START WITH 1 INCREMENT BY 1;

-- ******* CUSTOMERS_LOCATIONS ******

CREATE TABLE CUSTOMERS_LOCATIONS (
    CL_ID		INT NOT NULL PRIMARY KEY,
    LT_ID    	INT NOT NULL,
	STREET_ADDRESS VARCHAR2(20) NOT NULL,
    CITY   	VARCHAR2(20) NOT NULL,
	STATE		VARCHAR2(15) NOT NULL,
	ZIP_CODE	VARCHAR2(5) NOT NULL, 
	C_ID		INT NOT NULL,           
	CONSTRAINT C_ID_FK FOREIGN KEY (C_ID) REFERENCES CUSTOMERS(C_ID)
	ON DELETE CASCADE,
	CONSTRAINT LT_ID_FK FOREIGN KEY (LT_ID) REFERENCES LOCATIONS_TYPES(LT_ID)
	ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_CUS_LOC MINVALUE 1 START WITH 1 INCREMENT BY 1;

-- ******* MEAL_TYPES ******

CREATE TABLE MEAL_TYPES (
    MT_ID INT,
    NAME VARCHAR(25),
	PRIMARY KEY(MT_ID),
	CONSTRAINT UNIQUE_MN UNIQUE(NAME)
);

CREATE SEQUENCE SEQ_MEAL_TYPES MINVALUE 1 START WITH 1 INCREMENT BY 1;

-- ******* MEALS ******

CREATE TABLE MEALS (
    M_ID INT PRIMARY KEY,
    DESCRIPTION	VARCHAR(120) NOT NULL,
	NAME VARCHAR2(20) NOT NULL,
    PRICE DECIMAL(5,2) NOT NULL,
    IMAGE_PATH VARCHAR2(255) NOT NULL,
	MEAL_OF_DAY	DATE,
	MT_ID INT NOT NULL,
	CONSTRAINT MT_ID_FK FOREIGN KEY(MT_ID) REFERENCES MEAL_TYPES(MT_ID)
);

CREATE SEQUENCE SEQ_MEALS MINVALUE 1 START WITH 1 INCREMENT BY 1;

-- ******* ORDER_STATUS ******

CREATE TABLE ORDER_STATUS (
    OS_ID INT,
    NAME VARCHAR(25),
	PRIMARY KEY(OS_ID),
	CONSTRAINT UNIQUE_OSN UNIQUE(NAME)
);

CREATE SEQUENCE SEQ_ORDER_STAT MINVALUE 1 START WITH 1 INCREMENT BY 1;

-- ******* ORDERS ******

CREATE TABLE ORDERS(
	O_ID	INT NOT NULL PRIMARY KEY,
	ORDER_DATE	DATE NOT NULL ,
	DELIVERY_DATE	DATE NOT NULL,
	ORDER_ON_HOLD	CHAR(1 BYTE),
	TIMES_CHANGED	INT DEFAULT 0,
	C_ID INT NOT NULL,
	OS_ID INT NOT NULL,
	CL_ID INT NOT NULL,
	CONSTRAINTS C_ID_FK2 FOREIGN KEY(C_ID) REFERENCES CUSTOMERS(C_ID)
	ON DELETE CASCADE,
	CONSTRAINTS OS_ID_FK FOREIGN KEY(OS_ID) REFERENCES ORDER_STATUS(OS_ID)
	ON DELETE CASCADE,
	CONSTRAINTS CL_ID_FK FOREIGN KEY(CL_ID) REFERENCES CUSTOMERS_LOCATIONS(CL_ID)
	ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_ORDERS MINVALUE 1 START WITH 1 INCREMENT BY 1;

-- ******* ORDER_MEALS ******

CREATE TABLE ORDER_MEALS (
    OM_ID INT NOT NULL PRIMARY KEY,
	M_ID INT NOT NULL,
	O_ID INT NOT NULL,
	QUANTITY INT DEFAULT 1,
	CONSTRAINT M_ID_FK2 FOREIGN KEY(M_ID) REFERENCES MEALS(M_ID),
	CONSTRAINT O_ID_FK2 FOREIGN KEY(O_ID) REFERENCES ORDERS(O_ID)
);

CREATE SEQUENCE SEQ_ORDER_MEALS MINVALUE 1 START WITH 1 INCREMENT BY 1;

-- ******* PAYMENT_TYPES ******

CREATE TABLE PAYMENT_TYPES (
    PT_ID		INT PRIMARY KEY,
    PAYMENT_NAME	VARCHAR2(30),
	CONSTRAINT UNIQUE_PTN UNIQUE(PAYMENT_NAME)
);

CREATE SEQUENCE SEQ_PAY_TYPES MINVALUE 1 START WITH 1 INCREMENT BY 1;

-- ******* PAYMENTS ******

CREATE TABLE PAYMENTS (
    P_ID INT NOT NULL,
    PT_ID INT NOT NULL,
	O_ID INT NOT NULL,
	PRIMARY KEY(P_ID,O_ID),
	CONSTRAINT PT_ID_FK FOREIGN KEY(PT_ID) REFERENCES PAYMENT_TYPES(PT_ID)
	ON DELETE CASCADE,
	CONSTRAINT O_ID_FK FOREIGN KEY(O_ID) REFERENCES ORDERS(O_ID)
	ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_PAY MINVALUE 1 START WITH 1 INCREMENT BY 1;

-- ******* CARD_TYPES ******

CREATE TABLE CARD_TYPES(
	CT_ID	INT NOT NULL PRIMARY KEY,
	NAME	VARCHAR2(40),
	CONSTRAINT UNIQUE_CTN UNIQUE(NAME)
);

CREATE SEQUENCE SEQ_CARD_TYPES MINVALUE 1 START WITH 1 INCREMENT BY 1;

-- ******* CREDIT_CARDS ******

CREATE TABLE CREDIT_CARDS(
	CC_ID INT NOT NULL PRIMARY KEY,
	NAME_ON_CARD	VARCHAR2(100),
	CARD_NUMBER	VARCHAR2(16),
	CT_ID		INT NOT NULL,
	CONSTRAINT CT_ID_FK FOREIGN KEY(CT_ID) REFERENCES CARD_TYPES(CT_ID)
	ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_CREDIT_CARDS MINVALUE 1 START WITH 1 INCREMENT BY 1;

-- ******* CUSTOMERS_CREDIT_CARDS ******

CREATE TABLE CUSTOMERS_CREDIT_CARDS(
	CC_ID	INT NOT NULL,
	C_ID	INT NOT NULL,
	CONSTRAINT CC_ID_FK FOREIGN KEY(CC_ID) REFERENCES CREDIT_CARDS(CC_ID)
	ON DELETE CASCADE,
	CONSTRAINT C_ID2_FK FOREIGN KEY(C_ID) REFERENCES CUSTOMERS(C_ID)
	ON DELETE CASCADE,
	PRIMARY KEY(CC_ID,C_ID)
);

CREATE SEQUENCE SEQ_CUS_CRE_CARDS MINVALUE 1 START WITH 1 INCREMENT BY 1;

-- ******* CREDIT_CARD_DETAILS ******

CREATE TABLE CREDIT_CARD_DETAILS(
	P_ID	INT NOT NULL,
	CC_ID	INT NOT NULL,
	O_ID    INT NOT NULL,
	CONSTRAINT CC_ID2_FK FOREIGN KEY(CC_ID) REFERENCES CREDIT_CARDS(CC_ID)
	ON DELETE CASCADE,
	CONSTRAINT P_ID_FK FOREIGN KEY(P_ID,O_ID) REFERENCES PAYMENTS(P_ID, O_ID)
	ON DELETE CASCADE,
	PRIMARY KEY(P_ID)
);

CREATE SEQUENCE SEQ_CREDIT_CARD_DET MINVALUE 1 START WITH 1 INCREMENT BY 1;

-- ******* DELIVERING_POINTS ******

CREATE TABLE DELIVERING_POINTS (
    DP_ID		INT NOT NULL,
    STREET_ADDRESS VARCHAR2(20) NOT NULL,
	CITY      	VARCHAR2(20) NOT NULL,
    STATE      	VARCHAR2(15) NOT NULL,
    ZIP_CODE  	CHAR(5),
    PHONE_NUMBER    NUMBER(9) NOT NULL,
	PRIMARY KEY (DP_ID)
);

CREATE SEQUENCE SEQ_DEL_POINTS MINVALUE 1 START WITH 1 INCREMENT BY 1;

-- ******* CUSTOMER_PROFILES ******

CREATE TABLE CUSTOMER_PROFILES (
    CP_ID	   INT NOT NULL,
	PRIMARY KEY (CP_ID)
);

CREATE SEQUENCE SEQ_CUS_PRO MINVALUE 1 START WITH 1 INCREMENT BY 1;


-- ******* POPULATE TABLES *******

-- POPULATE CUSTOMERS TABLE --

INSERT INTO CUSTOMERS(C_ID,FIRST_NAME,LAST_NAME,PASSWORD,LAST_LOGIN,EMAIL,HOME_NUMBER,MOBILE_NUMBER)
	VALUES(SEQ_CUSTOMERS.NEXTVAL, 'David', 'Portillo', 'password1', '21/JAN/2017 04:00:00', 'david@gmail.com', 230300020, 453043204);
INSERT INTO CUSTOMERS(C_ID,FIRST_NAME,LAST_NAME,PASSWORD,LAST_LOGIN,EMAIL,HOME_NUMBER,MOBILE_NUMBER)
	VALUES(SEQ_CUSTOMERS.NEXTVAL, 'Lawrence', 'Broomfield', 'password1', '21/JAN/2017 04:00:00', 'lawrence@gmail.com', 345246642, 964739432);
INSERT INTO CUSTOMERS(C_ID,FIRST_NAME,LAST_NAME,PASSWORD,LAST_LOGIN,EMAIL,HOME_NUMBER,MOBILE_NUMBER)
	VALUES(SEQ_CUSTOMERS.NEXTVAL, 'Franklin', 'Berry', 'password1', '21/JAN/2017 04:00:00', 'Franklin@gmail.com', 947582443, 534254321);

-- POPULATE LOCATIONS_TYPES

INSERT INTO LOCATIONS_TYPES(LT_ID,LOCATION_NAME) VALUES(SEQ_LOC_TYPES.NEXTVAL, 'Billing');
INSERT INTO LOCATIONS_TYPES(LT_ID,LOCATION_NAME) VALUES(SEQ_LOC_TYPES.NEXTVAL, 'Residencial');

-- POPULATE CUSTOMERS_LOCATIONS 

INSERT INTO CUSTOMERS_LOCATIONS(CL_ID,LT_ID,STREET_ADDRESS,CITY,STATE,ZIP_CODE,C_ID) 
	VALUES(SEQ_CUS_LOC.NEXTVAL, 1, 'Fake Address','Arlington', 'VA', '22207', 1);
INSERT INTO CUSTOMERS_LOCATIONS(CL_ID,LT_ID,STREET_ADDRESS,CITY,STATE,ZIP_CODE,C_ID) 
	VALUES(SEQ_CUS_LOC.NEXTVAL, 2, 'Fake Address','Phoenix', 'AZ', '87887', 1);
INSERT INTO CUSTOMERS_LOCATIONS(CL_ID,LT_ID,STREET_ADDRESS,CITY,STATE,ZIP_CODE,C_ID) 
	VALUES(SEQ_CUS_LOC.NEXTVAL, 2, 'Fake Address','MyCity', 'MyState', '23424', 2);
INSERT INTO CUSTOMERS_LOCATIONS(CL_ID,LT_ID,STREET_ADDRESS,CITY,STATE,ZIP_CODE,C_ID) 
	VALUES(SEQ_CUS_LOC.NEXTVAL, 1, 'Fake Address','Kentucky City', 'Kentucky', '23424', 3);

-- POPULATE MEAL_TYPES

INSERT INTO MEAL_TYPES(MT_ID,NAME)
	VALUES (SEQ_MEAL_TYPES.NEXTVAL,'Vegan');
INSERT INTO MEAL_TYPES(MT_ID,NAME)
	VALUES(SEQ_MEAL_TYPES.NEXTVAL,'Non-Vegan');

-- POPULATE ORDER STATUS

INSERT INTO ORDER_STATUS(OS_ID,NAME)
	 VALUES(SEQ_ORDER_STAT.NEXTVAL, 'PENDING');
INSERT INTO ORDER_STATUS(OS_ID,NAME)
	 VALUES(SEQ_ORDER_STAT.NEXTVAL, 'DELIVERED');







