-- ******* DATABASE CONFIGURATION *******

CONNECT SA AS SYSDBA;

CREATE TABLESPACE new_tablespace28
DATAFILE 'C:\TEST\DATABASE28_FILE.dbf'
SIZE 20M AUTOEXTEND ON;

CREATE USER db_u28
IDENTIFIED BY pass
DEFAULT TABLESPACE new_tablespace26
/

GRANT DBA TO db_u28
/

CONNECT db_u28/pass